FROM node:14.2.0 as builder
MAINTAINER Hauke Stieler<mail@hauke-stieler.de>

RUN npm i -g @angular/cli

COPY package.json /tmp/package.json
COPY package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm install

RUN mkdir /stm-client
WORKDIR /stm-client/
RUN cp -r /tmp/node_modules ./
