version: '3.4'

services:
  stm-server:
    image: simpletaskmanager/stm-server:1.6.1-SNAPSHOT.2
    container_name: stm-server
    environment:
      - STM_OAUTH2_CLIENT_ID
      - STM_OAUTH2_SECRET
      - STM_DB_USERNAME
      - STM_DB_PASSWORD
      - STM_DB_HOST
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - $STM_SERVER_CONFIG:/stm-server/config.json
# 2020-12-09 hauke96: See systemd issue below
#    depends_on:
#      - "stm-db"
    logging:
      driver: 'journald'
  stm-client:
    image: simpletaskmanager/stm-client:1.6.1-SNAPSHOT.2
    container_name: stm-client
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - $STM_NGINX_CONFIG:/etc/nginx/conf.d/default.conf
      # This allows you to show arbitrary notes on the login screen (e.g. to inform user about maintenance):
      #- ./notice.de.html:/usr/share/nginx/html/assets/i18n/notice.de.html
    logging:
      driver: 'journald'
  stm-db:
    image: postgres:12
    container_name: stm-db
    restart: unless-stopped
    network_mode: host
    environment:
      - POSTGRES_USER=${STM_DB_USERNAME}
      - POSTGRES_PASSWORD=${STM_DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
# 2020-12-09 hauke96: Because health checks are creating mount points, newer
# systemd versions are flodding the logs with succeed-messages rendering the
# logs more or less useless, because they are way too large. I disable health
# checks here until there's a solution for that.
#
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${STM_DB_USERNAME}"]
#      interval: 1s
#      timeout: 2s
#      retries: 30
#      start_period: 1s
    logging:
      driver: 'journald'
