@startuml

package main <<Frame>> {
    class main.main
}

package util <<Frame>> {
    class util.util
}

package config <<Frame>> {
    class config.config
}

package api <<Frame>> {
    class api.api {
    }
    class api.api_vX {
    }

    api.api --> api.api_vX

    api.api_vX --> project.project
    api.api_vX --> task.task
}

package auth <<Frame>> {
    class auth.auth {
    }

    class auth.token {
    }

    auth.auth --> auth.token
}

package project <<Frame>> {
    class project.project {
    }

    class project.project_store_pg {
    }

    project.project --> project_store_pg
}

package task <<Frame>> {
    class task.task {
    }

    class task.task_store_pg {
    }

    task.task --> task_store_pg
}

package permission <<Frame>> {
    class permission.permission{
    }
}

main.main --> api.api : Init()
main.main --> auth.auth : Init()
main.main --> project : Init()
main.main --> task : Init()
main.main --> permission : Init()

api.api --> auth.auth
api.api_vX --> auth.auth

task.task --> permission.permission

project.project --> task.task
project.project --> permission.permission
project.project_store_pg --> task.task


@enduml