@startuml

package main <<Frame>> {
    class main.main
}

package util <<Frame>> {
    class util.util
}

package config <<Frame>> {
    class config.config
}

package websocket <<Frame>> {
    class websocket.websocket
}

' Alignment:
main -[hidden]down- util
main -[hidden]right- websocket
util -[hidden]right- config

package api <<Frame>> {
    class api.api {
    }
    class api.api_vX {
    }

    api.api --> api.api_vX

    api.api_vX --> project.service
    api.api_vX --> task.service
    api.api_vX --> export.service
}

package auth <<Frame>> {
    class auth.auth {
    }

    class auth.token {
    }

    auth.auth --> auth.token
}

package project <<Frame>> {
    class project.service {
    }

    class project.store {
    }

    project.service --> store
}

package task <<Frame>> {
    class task.service {
    }

    class task.store {
    }

    task.service --> store
}

package export <<Frame>> {
    class export.service{
    }
}

package permission <<Frame>> {
    class permission.store{
    }
}

'main.main --> api.api : Init()
'main.main --> auth.auth : Init()
'main.main --> project : Init()
'main.main --> task : Init()
'main.main --> permission : Init()

api.api --> auth.auth
api.api_vX --> auth.auth

task.service --> permission.store

project.service --> task.service
project.service --> permission.store
project.store --> task.service

export.service --> project.service

@enduml