BEGIN TRANSACTION;

ALTER TABLE tasks ADD COLUMN project_id int;
ALTER TABLE tasks ADD CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;

INSERT INTO db_versions VALUES('006');

END TRANSACTION;